apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    server: https://api.{{ getenv "KOPS_CLUSTER_NAME" }}
    certificate-authority-data: {{ getenv "KOPS_CERTIFICATE_AUTHORITY_DATA" }}
  name: {{ getenv "KOPS_CLUSTER_NAME" }}

contexts:
- context:
    cluster: {{ getenv "KOPS_CLUSTER_NAME" }}
    user: {{ getenv "KOPS_CLUSTER_NAME" }}
  name: {{ getenv "KOPS_CLUSTER_NAME" }}

current-context: {{ getenv "KOPS_CLUSTER_NAME" }}

users:
- name: {{ getenv "KOPS_CLUSTER_NAME" }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
      - token
      - -i
      - {{ getenv "KOPS_CLUSTER_NAME" }}
